import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const hkGrotesk = localFont({
  src: [
    {
      path: '../../public/fonts/hk-grotesk/HKGrotesk-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/hk-grotesk/HKGrotesk-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/hk-grotesk/HKGrotesk-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/hk-grotesk/HKGrotesk-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/hk-grotesk/HKGrotesk-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-grotesk',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hkGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
